name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  argv: 
    description: 'argv'
    required: true
    default: '{}'
  config: 
    description: 'config'
    required: true
    default: '{}'
    
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'dist/index.js'
